### PR TITLE
Add application name to subcommand help template

### PR DESCRIPTION
**Pull request by radeksimko**
This will make the help text more helpful for users.

### CODE REVIEW

**Comment by vieux** [comment]
:+1:

**Comment by jszwedko** [comment]
I don't think this would work as expected for nested subcommands (you would just get the "parent" subcommand in the output as the `AppName`).

**Comment by radeksimko** [comment]
@jszwedko Good point, do you have any example of nested subcommands, so we can come up with appropriate solution for that as well?

**Comment by jszwedko** [comment]
@radeksimko sorry for the delay.

Example:
```go
package main

import (
  "os"
  "github.com/codegangsta/cli"
)

func main() {
  app := cli.NewApp()
  app.Name = "greet"
  app.Usage = "fight the loneliness!"
  app.Commands = []cli.Command{
  {
    Name:      "add",
    ShortName: "a",
    Usage:     "add a task to the list",
    Action: func(c *cli.Context) {
      println("added task: ", c.Args().First())
    },
  },
  {
    Name:      "complete",
    ShortName: "c",
    Usage:     "complete a task on the list",
    Action: func(c *cli.Context) {
      println("completed task: ", c.Args().First())
    },
  },
  {
    Name:      "template",
    ShortName: "r",
    Usage:     "options for task templates",
    Subcommands: []cli.Command{
      {
        Name:  "add",
        Usage: "add a new template",
        Action: func(c *cli.Context) {
            println("new task template: ", c.Args().First())
        },
      },
      {
        Name:  "remove",
        Usage: "remove an existing template",
        Action: func(c *cli.Context) {
          println("removed task template: ", c.Args().First())
        },
      },
    },
  },     
}

  app.Run(os.Args)
}
```

**Comment by jszwedko** [comment]
Note that I just frakenstein'd this from the README so it may not compile, but hopefully it gives you an idea.

**Comment by JohnMaguire** [comment]
@jszwedko @radeksimko Err, not quite. I had almost the exact same solution at first. And it actually would work, because, as you'll see [here](https://github.com/codegangsta/cli/blob/30b361bf66a60174a9589458afbf494478bafd00/command.go#L142-L146), the Name gets set when `startApp()` is called on the Command.

Which means the real bug is that the name from the previous command doesn't get prepended if "help" is called, because "help" is a different sub-command (thus, `startApp()` isn't called, and the Name isn't set.)

I'm about to submit a pull request in a moment with a modified patch.

**Comment by jszwedko** [comment]
I believe this is addressed by #246, let me know what you think @radeksimko

**Comment by radeksimko** [comment]
Looks :ok_hand:

**Pull request closed without merging**
