### PR TITLE
Provide a variable for writing output (the writer) with a default of os.Stderr

### PR DESCRIPTION
**Pull request by mattfarina**
This allows:

- Users to set their own writer (e.g., to wrap the text or send it elsewhere such as a log)
- Allows tests to capture the output and check responses.

### CODE REVIEW

**Comment by meatballhat** [comment]
@mattfarina Thanks for the PR!  I would support this if it were implemented similarly to `App.Writer`.  Perhaps `App.ErrorWriter`?

**Comment by mattfarina** [comment]
@meatballhat There are several places a change like that would work. I'm not sure how to apply it to the `Apply` method on `IntSliceFlag` or inside `HandleExitCoder`. Do you have any guidance on those cases?

**Comment by meatballhat** [comment]
How about defining ErrorWriter as both a package level var and a member of
App?  nil at the App level falls back to package level value.  Sound OK?

**Comment by mattfarina** [comment]
@meatballhat I used `ErrWriter` (shortening Error because it's the Go pattern). Is the nil check an acceptable pattern?

**Comment by jszwedko** [comment]
:+1: this seems reasonable to me

**Comment by meatballhat** [comment]
Lovely! 👍

**Pull request merged**
