### PR TITLE
Really skip flag parsing

### PR DESCRIPTION
**Pull request by jszwedko**
See #278 for where this was brought up.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
So I think I tried this solution and the issue I would always run into is that `c.Args` stops working completely when `SkipFlagParsing` is set to `true`.  Now, granted, I may be misunderstanding how it's meant to work, but I would assume `c.Args()` would still return values (including the literal flag args) if `SkipFlagParsing` is set to `true`.

For instance consider this example:

```golang
package main

import (
	"fmt"
	"os"

	"github.com/codegangsta/cli"
)

func main() {
	app := cli.NewApp()
	app.Name = "foo"
	app.Commands = []cli.Command{
		{
			Name:            "bar",
			SkipFlagParsing: true,
			Action: func(c *cli.Context) {
				fmt.Println(c.Args())
			},
		},
	}

	app.Run(os.Args)
}
```

I compiled your PR into separate binaries with and without the `SkipFlagParsing` option.

```console
$ ./skip bar a b c
[]
$ ./noskip bar a b c
[a b c]
```

Whereas compiled with master today it _does_ work:

```console
$ ./skip bar a b c
[a b c]
$ ./skip bar a b --foo c
[a b --foo c]
```

If this is expected behavior that's OK, and maybe I should just use `os.Args` directly in this case, but I wanted to make sure you're advised of this change in behavior before merging in this PR.

**Comment by jszwedko** [comment]
@nathanleclaire mmm, you are correct. I think it would be best to try to keep the arguments in `.Args()`, but this may prove difficult as the call on `Context` currently just delegates to the `FlagSet`. Let me give it a shot.

**Comment by jszwedko** [comment]
Not crazy about the implementation, but it seemed like the least invasive to do as I did in https://github.com/codegangsta/cli/commit/845c83453c000f2fdf729e7f7bad7e2b1703ce4e. Thanks bringing this up!

**Comment by nathanleclaire** [comment]
Cool.  I'll try the code out and get back to you on how it looks from our end.

**Comment by nathanleclaire** [comment]
Everything looks good with this patch that I've tried so far.  It fixes an issue I was running into where `--help` was being parsed in spite of `SkipFlagParsing` as well (maybe you want to add a test for that too?).  Thanks a bunch for taking the time to work on this @jszwedko !

**Comment by nathanleclaire** [comment]
I added a test for `--help` case and also to revise to use a test table (cleaner) here: https://github.com/codegangsta/cli/pull/291 if you are interested @jszwedko

**Comment by nathanleclaire** [comment]
I think I'm still running into some issues with e.g. `-h` with this patch, strangely. I would expect `-h` to be skipped as well, and I though the additional test covered that, but maybe not.

**Comment by nathanleclaire** [comment]
@jszwedko Any update on this?

**Comment by jszwedko** [comment]
Hey @nathanleclaire, apologies for the delay! I wasn't able to reproduce this using the above snippet and this branch, i.e:

```
package main

import (
    "fmt"
    "os"

    "github.com/codegangsta/cli"
)

func main() {
    app := cli.NewApp()
    app.Name = "foo"
    app.Commands = []cli.Command{
        {
            Name:            "bar",
            SkipFlagParsing: true,
            Action: func(c *cli.Context) {
                fmt.Println(c.Args())
            },
        },
    }

    app.Run(os.Args)
}
```

```
$ go run -a /tmp/tmp.go bar -h
[-h]
```

Is there something I'm missing?

**Comment by nathanleclaire** [comment]
Oh boy... I'm sorry, this is actually entirely on me: https://github.com/docker/machine/blob/master/commands/ssh.go#L12

:blush:

**Comment by nathanleclaire** [comment]
But at any rate, any ETA on merging this PR?

**Comment by jszwedko** [comment]
Haha :smile: , I think this is good to go now then! Merging.

**Comment by nathanleclaire** [comment]
:confetti_ball: :dancer: :dancers: :+1: :+1: :+1:

**Pull request merged**
