### PR TITLE
Allow commands to be hidden from help and autocomplete

### PR DESCRIPTION
**Pull request by psmit**
It would be great if commands can be hidden from the user. This PR does exactly that.

### CODE REVIEW

**Comment by jszwedko** [comment]
I understand the motivation for a feature like this, but this could also be accomplished by checking for an environment variable and conditionally adding commands in the source (e.g. looking for `HIDDEN_COMMANDS=1` and adding the commands if it is set).

**Comment by phsmit** [comment]
Sorry for getting back so late, I have been sick this week.

Actually, it is very hard to set enviroment variables sometimes. For example, in our use case, gogits/gogs, we need to call a subcommand as entry point for persons that connect through ssh. This means we add keys to ~/.ssh/authorized_keys with an appropriate command="". It is quite a hassle to get environment variables working well in such case.

I understand to keep the codebase clean and tidy, but this change is very small and I would very much appreciate if you could consider again merging this request.

**Comment by meatballhat** [comment]
Especially given the recent merge (by me!) of the hidden flags feature, I'd like to get this in.  I'm working on the merge resolution right now. :metal:

**Comment by jszwedko** [comment]
:+1: the use case makes sense to me -- apologies for losing track of this issue.

**Pull request closed without merging**
