### PR TITLE
Allow hiding default values.

### PR DESCRIPTION
**Pull request by jgeewax**
Also changes how defaults are shown.

### CODE REVIEW

**Comment by jacobsa** [comment]
@codegangsta: Are you able to take a look at these changes? They would be quite helpful for GoogleCloudPlatform/gcsfuse. In particular, we need to hide the default for a flag (mount options, `-o`) that can be repeated and doesn't really have a default per se.

**Comment by jgeewax** [comment]
It's fine to depend on my fork while we wait though, right ?

**Comment by jacobsa** [comment]
Right, it's just the usual issue of drift from upstream; I'd like to depend on the official one sooner rather than later.

**Comment by jszwedko** [comment]
@jgeewax thanks! I like the idea, but I'm not crazy about adding more conditional logic there to support a different "format". I think what may be a more flexible approach would be to have a configurable template that would be executed that could be set at the `App` or maybe even the `Flag` level that way we can support your use case as well as future cases where users want to change the flag usage format.

**Comment by jszwedko** [comment]
If I find some time I'll try to spike out that approach.

**Comment by jgeewax** [comment]
Cool - I'm +1 to that. Letting people specify a template for each item sounds like a great plan.

**Pull request closed without merging**
