### PR TITLE
Add support for multiple authors

### PR DESCRIPTION
**Pull request by paked**
Through the addition of a new Author struct, I have added support for multiple Authors. This, however, is change to the API (although, it could be averted if wanted?)

### CODE REVIEW

**Comment by jszwedko** [comment]
I like this addition. It is a change to the API though, so I'll mark it to be included in the next round of API breaking changes. We could get this change in sooner if we maintained the old API, but also allowed for a list to be specified.

**Comment by jszwedko** [comment]
i.e. keep `Author` and `Email`, but also add `Authors` with a note in the doc comments warning people away from using `Author` and `Email`.

**Comment by paked** [comment]
Just added support for this. If ```Author``` and ```Email``` are set app.Run will append an ```Author``` object onto the ```Authors``` list.

**Comment by jszwedko** [comment]
I branched off this to merge in master to eliminate conflicts in #192. Thank you for this!

**Pull request merged**
